### PR TITLE
Created a test demo script

### PR DESCRIPTION
**Pull request by sachinkamlanil**
For demo purposes

### CODE REVIEW

**Comment by sachinkamlanil** [comment]
I have made a commit to demo a test shell script

**Comment by sachinkamlanil** [comment]
Ashish: No, I do not like the echo part, please correct it

**Comment by sachinkamlanil** [comment]
Rupali: IGTM -> Looks good to me

**Comment by spidy17** [comment]
test

**Comment by ashusanvatsarkar** [comment]
Comment

**Comment by Jagdishwani05** [comment]
Hi these is my first conversation on github.

**Pull request merged**
